services:
  languagetool:
    # image: erikvl87/languagetool
    image: languagetool:latest
    container_name: languagetool
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEFAULT_LANG=fr_FR.UTF-8
    restart: unless-stopped
    ports:
      - 8010:8010
    environment:
      - langtool_languageModel=/ngrams
      - langtool_motherTongue=fr
      - Java_Xms=512m
      - Java_Xmx=1g
    volumes:
      - ./data/ngrams:/ngrams:ro
      - ./data/dict:/dict/:ro
      #- ./path/to/logback.xml:/LanguageTool/logback.xml:ro
    #command: "tail -f /dev/null"
